apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-engine
  namespace: wireless-security-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detection-engine
  template:
    metadata:
      labels:
        app: detection-engine
    spec:
      containers:
      - name: detection-engine
        image: wireless-security-platform-detection-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: detection-engine
  namespace: wireless-security-platform
spec:
  selector:
    app: detection-engine
  ports:
  - name: http
    port: 8001
    targetPort: 8001
