apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - grafana.yaml
  - prometheus-configmap.yaml
  - prometheus.yaml
  - detection-engine.yaml
  - telemetry-api.yaml
  - sensor-agent.yaml
