apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: wireless-security-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: telemetry_api
      metrics_path: /metrics
      static_configs:
      - targets: ['telemetry-api:8000']
