apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-agent
  namespace: wireless-security-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sensor-agent

  template:
    metadata:
      labels:
        app: sensor-agent

    spec:
      containers:
      - name: sensor-agent
        image: wireless-security-platform-sensor-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TELEMETRY_API
          value: http://telemetry-api:8000/telemetry
        - name: SCAN_INTERVAL_SECONDS
          value: "60"